### PR TITLE
fail without summaries

### PR DESCRIPTION
**Pull request by hatkyinc2**
https://github.com/fjrdomingues/autopilot/issues/42

### CODE REVIEW

**Comment by lmsutools** [comment]
Hi, I'm runningthe latest commit and the problem persists
image


Do I have my project folder in the right format in the .env? 
I'm on Windows.
CODE_DIR=C:\GitTests\Lamassu-Licensing-Server

I might think yes, the .ai.txt files are being generated correctly.

**Comment by hatkyinc2** [comment]
@lmsutools Weird thing about windows code path currently you have to use POSIX format
`CODE_DIR=C:/Users/hatky/code/public/autopilot`

**Comment by hatkyinc2** [comment]
so your config should be

`CODE_DIR=C:/GitTests/Lamassu-Licensing-Server`

**Comment by hatkyinc2** [comment]
Added explanation in https://github.com/fjrdomingues/autopilot/pull/49
@lmsutools

**Pull request merged**
